filetype on
syntax on
colorscheme Tomorrow-Night
set guifont=Menlo\ Regular:h18
set number
set hidden
set history=100
filetype indent on
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
set wildignore+=*.log,*.sql,*.cache
